server:
  port: 0

spring:
#  config:
#    import: "optional:configserver:http://127.0.0.1:8888"
  cloud:
#    config:
#      name: ecommerce
    openfeign:
      micrometer:
        enabled: true

  application:
    name: user-service
#  profiles:
#    active: dev

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username : guest
    password : guest



#  datasource:
    #url: jdbc:h2:tcp://localhost/~/desktop/study/h2/jpashop
#    url: 'jdbc:h2:mem:testdb'   # H2 DB 연결 주소 (In-Memory Mode)
#    url: 'jdbc:h2:~/user-db'    # H2 DB 연결 주소 (Embedded Mode)
#    username: sa
#    password: 921013
#    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true #h2 사용
      settings:
        web-allow-others: true #h2외부 접속 허용
      path: /h2-console #경로 설정

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: validate



  # api-key 인증 정보 설정
  security:
    basic:
      key : password # $2a$10$atrV7lklwrGOFpELZ3fIveDW7z2oSr71p6MMvn8RcDvDWgAyRN.z.

  #spring boot 2.x 에서 사용하는 zipkin설정
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0  # 모든 요청에 대해 추적 (프로덕션에서는 낮은 값 사용 권장, 예: 0.1)


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce. (spring boot)

#token:
#  expiration_time: 86400000 #10 days
#  secret : my-very-long-secret-key-1234567890123456

management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청에 대해 추적 (프로덕션에서는 낮은 값 사용 권장, 예: 0.1)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # Zipkin 서버 주소
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus, httptrace

logging:
  level:
    com.example.userservice.client : DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"  # 로그에 트레이스 ID와 스팬 ID 포함

